/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libcamera_apps_LibcameraApps */

#ifndef _Included_org_libcamera_apps_LibcameraApps
#define _Included_org_libcamera_apps_LibcameraApps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    setOptions
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_setOptions
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    openCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_openCamera
  (JNIEnv *, jclass);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    closeCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_closeCamera
  (JNIEnv *, jclass);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    configureViewfinder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_configureViewfinder
  (JNIEnv *, jclass);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    configureStill
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_configureStill
  (JNIEnv *, jclass);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    configureVideo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_configureVideo
  (JNIEnv *, jclass);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    teardown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_teardown
  (JNIEnv *, jclass);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    retrive
 * Signature: (Lorg/libcamera/apps/Frame;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_retrive
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
