/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libcamera_apps_LibcameraApps */

#ifndef _Included_org_libcamera_apps_LibcameraApps
#define _Included_org_libcamera_apps_LibcameraApps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libcamera_apps_LibcameraApps_init
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    setOptions
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_setOptions
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    openCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_openCamera
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    startCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_startCamera
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    stopCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_stopCamera
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    closeCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_closeCamera
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    configureViewfinder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_configureViewfinder
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    configureStill
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_configureStill__
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    configureVideo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_configureVideo__
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    configureStill
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_configureStill__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    configureVideo
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_configureVideo__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    teardown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_teardown
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    retrive
 * Signature: (Lorg/libcamera/apps/Frame;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_retrive
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    configureCustomVideo
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libcamera_apps_LibcameraApps_configureCustomVideo
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    setRoi
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_libcamera_apps_LibcameraApps_setRoi
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    resetRoi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libcamera_apps_LibcameraApps_resetRoi
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    focusManual
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_org_libcamera_apps_LibcameraApps_focusManual
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    focusAuto
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_org_libcamera_apps_LibcameraApps_focusAuto
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    focusContinuesAuto
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_org_libcamera_apps_LibcameraApps_focusContinuesAuto
  (JNIEnv *, jobject);

/*
 * Class:     org_libcamera_apps_LibcameraApps
 * Method:    triggerFocus
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_org_libcamera_apps_LibcameraApps_triggerFocus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
